# Generated by Django 5.1.6 on 2025-06-01 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Letters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('open_date', models.DateField()),
                ('category', models.CharField(choices=[('past', '과거'), ('today', '오늘'), ('future', '미래')], default='future', max_length=20)),
                ('mood', models.CharField(blank=True, choices=[('joy', '기쁨'), ('sadness', '슬픔'), ('anger', '분노'), ('anxiety', '불안'), ('love', '사랑'), ('neutral', '중립')], max_length=30, null=True)),
                ('detailed_mood', models.CharField(blank=True, choices=[('ecstasy', '희열'), ('satisfaction', '만족'), ('gratitude', '감사'), ('excitement', '설렘'), ('loneliness', '외로움'), ('loss', '상실감'), ('regret', '후회'), ('annoyance', '짜증'), ('rage', '분개'), ('resentment', '억울함'), ('fear', '두려움'), ('nervousness', '긴장'), ('restlessness', '초조'), ('romance', '로맨스'), ('friendship', '우정'), ('respect', '존경')], max_length=30, null=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
