# Generated by Django 5.1.6 on 2025-05-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letters',
            name='image',
        ),
        migrations.AddField(
            model_name='letters',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
