# Generated by Django 5.1.6 on 2025-05-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionresult',
            name='letter_id',
            field=models.IntegerField(default=0),
        ),
    ]
