# Generated by Django 5.1.6 on 2025-05-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_emotionresult_letter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionresult',
            name='most_frequent_mood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
