# Generated by Django 5.1.6 on 2025-05-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionresult',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
