# Generated by Django 5.1.6 on 2025-05-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_emotionresult_analyzed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionresult',
            name='most_frequent_mood',
            field=models.CharField(default='기쁨', max_length=100),
            preserve_default=False,
        ),
    ]
