# Generated by Django 5.1.6 on 2025-05-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_emotionresult_most_frequent_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionresult',
            name='most_frequent_detailed_mood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
