# Generated by Django 5.1.6 on 2025-05-25 00:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_emotionresult_most_frequent_detailed_mood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotionresult',
            old_name='emotion_scores',
            new_name='emotions',
        ),
        migrations.RemoveField(
            model_name='emotionresult',
            name='detailed_emotion',
        ),
        migrations.RemoveField(
            model_name='emotionresult',
            name='dominant_emotion',
        ),
        migrations.RemoveField(
            model_name='emotionresult',
            name='letter_id',
        ),
        migrations.AddField(
            model_name='emotionresult',
            name='comfort_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emotionresult',
            name='analyzed_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
