# Generated by Django 5.1.6 on 2025-05-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LetterImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blob_name",
                    models.CharField(
                        help_text="GCS에 저장된 파일의 고유 경로",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        help_text="사용자가 업로드한 원본 파일의 이름",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        help_text="이미지 파일의 크기 (바이트)"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="이미지가 GCS에 업로드된 시간"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        help_text="이미지 파일의 Content-Type (MIME 타입)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "letter_id",
                    models.CharField(
                        blank=True, help_text="편지 고유 ID", max_length=100, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "첨부 이미지",
                "verbose_name_plural": "첨부 이미지들",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
